### ISSUE TITLE
netconfig installs scripts below /etc

### ISSUE THREAD

**Issue by thkukuk** [openSUSE/sysconfig#33]
netconfig installs scripts below /etc into /etc/netconfig.d and /etc/sysconfig/network/scripts

This scripts are no configuration files, they are not marked as config files and they break image based installation and update (image means /usr, not full disk images). This scripts should have never been there.

Better and FHS conform directories are:
* /usr/libexec/netconfig/netconfig.d/
* /usr/libexec/netconfig/scripts

Since there is only one other package using /etc/netconfig.d (cloud-netconfig) and admin made changes get overwritten with every update (without backup file), it should be no problem to change that.

**Comment by mtomaschewski** [comment]
A further step and  for now final step is in https://github.com/openSUSE/sysconfig/pull/41.

We can't change the location of the /etc/ppp/ip-up scripts as long as the pppd does not support other directories.

**Comment by mtomaschewski** [comment]
We can move the /etc/ppp/ip-up script to libexec and add support to execute the ip-up.d scripts in both, see https://github.com/openSUSE/sysconfig/pull/44

**Comment by mtomaschewski** [comment]
All scripts moved to /usr In https://github.com/openSUSE/sysconfig/releases/tag/version-0.90.0
