### ISSUE TITLE
Drop functions.rpm-utils

### ISSUE THREAD

**Issue by thkukuk** [openSUSE/sysconfig#34]
This is a shell function for sysconfig file handling itself, but:
- it's below /etc/sysconfig/network
- we have RPM macros everyobdy using
- I couldn't find any consumer on Tumbleweed
- it's not a config file and thus should be somewhere below /usr/libexec/sysconfig/...
- it's breaking image based installation and update (image = /usr)

We can fix it or drop it. Since there is no consumer, we should drop it.

**Comment by mtomaschewski** [comment]
I'll take a look, but after SLE-15-SP4 release.

**Comment by mtomaschewski** [comment]
We don't need them any more, thus dropped and merged to master in commit https://github.com/openSUSE/sysconfig/commit/d2bcbefeab60dcc3e1fc20aae41e1c0e391b895e
