### ISSUE TITLE
Shmem can't be freeed after many times for net iface hotplug

### ISSUE THREAD

**Issue by wengmeiling** [openSUSE/sysconfig#4]
Hi, 
When we test net iface  hotplug, we found that udev will call "/sbin/ifup $env{INTERFACE} -o hotplug"   and  produces a renamed file to mark the renaming was completed.But after many times net iface hotplug, there are mang new-stamps-\* files under /etc/.sysconfig/network/, and /proc/meminfo | grep Shmem increase much, and it can't be freed by echo 3 > /proc/sys/vm/drop_caches except delete the new-stamp\* files. 

But from the notes, I think this rename flag is just needed by network service onboot, so is it better to delete these files appropriately or just produce them onboot, so that it will not consume the  unnecessary memory?

**Comment by mtomaschewski** [comment]
See commit https://github.com/openSUSE/sysconfig/commit/4adb608

**Comment by mtomaschewski** [comment]
This one works for me and catches also cleanup in non-hotplug cases.
