### ISSUE TITLE
remove uas from /etc/modprobe.d/50-blacklist.conf

### ISSUE THREAD

**Issue by crrodriguez** [openSUSE/sysconfig#5]
Hi:

According to the kernel changelog, the UAS driver works properly now..
- Wed Jul 30 2014 jdelvare@suse.de
- Revert "config: disable USB_UAS (bnc#888069)."
  This reverts commit f509af67eb3a98665e0134eaadb91e93420d9e04. The uas
  driver works fine since kernel v3.15, the problem was that the
  module was blacklisted so it would not load when needed.
- commit 9b5a5f0

Suggest removing it from the blacklist.

**Comment by mtomaschewski** [comment]
this is  done long time ago.
